version: "3.9"

services:
  carta:
    image: nixx-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nixx-carta
    env_file:
      - /home/nixx/config/frontend-carta/.env
    environment:
      - NODE_ENV=production
    ports:
      # Mapea el puerto externo 3300 (por defecto) al puerto interno 3000 de Next.js
      - "${HOST_PORT:-3300}:3000"
    restart: unless-stopped

